2021-04-29 15:44:44 INFO run.py:219 GNS3 server version 2.2.20
2021-04-29 15:44:44 INFO run.py:221 Copyright (c) 2007-2021 GNS3 Technologies Inc.
2021-04-29 15:44:44 INFO run.py:224 Config file /home/saad/.config/GNS3/2.2/gns3_server.conf loaded
2021-04-29 15:44:44 WARNING run.py:230 Local mode is enabled. Beware, clients will have full control on your filesystem
2021-04-29 15:44:44 INFO run.py:243 Running with Python 3.9.3 and has PID 5639
2021-04-29 15:44:44 INFO run.py:79 Current locale is en_US.UTF-8
2021-04-29 15:44:44 WARNING port_manager.py:92 Remote console connections are allowed
2021-04-29 15:44:44 INFO web_server.py:318 Starting server on localhost:3080
2021-04-29 15:44:45 INFO __init__.py:63 Load controller configuration file /home/saad/.config/GNS3/2.2/gns3_controller.conf
2021-04-29 15:44:45 INFO __init__.py:67 Controller is starting
2021-04-29 15:44:45 INFO compute.py:64 Create compute local
2021-04-29 15:44:45 INFO compute.py:364 Connecting to compute 'local'
2021-04-29 15:44:45 INFO web_log.py:206 127.0.0.1 [29/Apr/2021:10:44:45 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 552 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:45 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:45 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:44:45 INFO notification_handler.py:50 New client has connected to compute WebSocket
2021-04-29 15:44:45 INFO compute.py:434 Connected to compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws'
2021-04-29 15:44:45 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:45 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:44:45 INFO notification_handler.py:73 New client has connected to controller WebSocket
2021-04-29 15:44:45 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:45 +0000] "GET /v2/templates HTTP/1.1" 200 21551 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:44:45 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:45 +0000] "GET /v2/appliances?symbol_theme=Affinity-circle-blue HTTP/1.1" 200 790748 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:44:45 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:45 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:44:45 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:45 +0000] "GET /v2/projects HTTP/1.1" 200 25584 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:44:45 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:45 +0000] "GET /v2/projects HTTP/1.1" 200 25584 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:44:49 INFO project.py:78 Project 5df9e162-2730-432e-95fa-67089a22eb5a with path '/home/saad/GNS3/projects/untitled' created
2021-04-29 15:44:49 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:49 +0000] "POST /v2/compute/projects HTTP/1.1" 201 303 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:49 INFO docker_vm.py:1058 Docker container "debian-1" [bd98c56c-92f5-4023-9b75-56727eb6ce82]: number of Ethernet adapters changed to 1
2021-04-29 15:44:50 INFO docker_vm.py:406 Docker container 'debian-1' [bd98c56c-92f5-4023-9b75-56727eb6ce82] created
2021-04-29 15:44:50 INFO web_log.py:206 127.0.0.1 [29/Apr/2021:10:44:49 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/docker/nodes HTTP/1.1" 201 924 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:50 INFO docker_vm.py:1058 Docker container "debian-2" [e113cdc9-d045-410f-9db0-56c48af947a3]: number of Ethernet adapters changed to 1
2021-04-29 15:44:50 INFO docker_vm.py:406 Docker container 'debian-2' [e113cdc9-d045-410f-9db0-56c48af947a3] created
2021-04-29 15:44:50 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:50 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/docker/nodes HTTP/1.1" 201 924 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:50 INFO __init__.py:303 Creating new hypervisor localhost:32837 with working directory /home/saad/GNS3/projects/untitled/project-files/dynamips
2021-04-29 15:44:50 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i1_log.txt', '-H', '32837']
2021-04-29 15:44:50 INFO hypervisor.py:129 Dynamips process logging to /home/saad/GNS3/projects/untitled/project-files/dynamips/dynamips_i1_stdout.txt
2021-04-29 15:44:50 INFO hypervisor.py:136 Dynamips process started PID=5700
2021-04-29 15:44:50 INFO __init__.py:305 Hypervisor localhost:32837 has successfully started
2021-04-29 15:44:50 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on localhost:32837 after 0.3829 seconds
2021-04-29 15:44:50 INFO router.py:222 Router c7200 "R1" [dedcf55c-74be-4781-9ab0-40961a359022] has been created
2021-04-29 15:44:50 INFO router.py:1102 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: adapter C7200-IO-FE inserted into slot 0
2021-04-29 15:44:50 INFO router.py:952 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: auto delete disks enabled
2021-04-29 15:44:50 INFO router.py:903 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: disk0 updated from 64MB to 0MB
2021-04-29 15:44:50 INFO router.py:661 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: idle-PC set to 0x606c8480
2021-04-29 15:44:50 INFO router.py:489 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: has a new IOS image set: "/home/saad/GNS3/images/IOS/c7200-is-mz.122-17a.image"
2021-04-29 15:44:50 INFO router.py:1027 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: MAC address updated from ca01.1644.0000 to ca01.7054.0000
2021-04-29 15:44:50 INFO router.py:543 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: NVRAM updated from 128KB to 512KB
2021-04-29 15:44:50 INFO router.py:516 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: RAM updated from 256MB to 512MB
2021-04-29 15:44:50 INFO router.py:1158 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: adapter C7200-IO-FE removed from slot 0
2021-04-29 15:44:50 INFO router.py:1102 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: adapter C7200-IO-2FE inserted into slot 0
2021-04-29 15:44:50 INFO router.py:1102 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: adapter PA-4T+ inserted into slot 1
2021-04-29 15:44:50 INFO web_log.py:206 127.0.0.1 [29/Apr/2021:10:44:50 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/dynamips/nodes HTTP/1.1" 201 1365 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:50 INFO __init__.py:303 Creating new hypervisor localhost:55457 with working directory /home/saad/GNS3/projects/untitled/project-files/dynamips
2021-04-29 15:44:50 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i2_log.txt', '-H', '55457']
2021-04-29 15:44:50 INFO hypervisor.py:129 Dynamips process logging to /home/saad/GNS3/projects/untitled/project-files/dynamips/dynamips_i2_stdout.txt
2021-04-29 15:44:50 INFO hypervisor.py:136 Dynamips process started PID=5716
2021-04-29 15:44:50 INFO __init__.py:305 Hypervisor localhost:55457 has successfully started
2021-04-29 15:44:50 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on localhost:55457 after 0.0117 seconds
2021-04-29 15:44:50 INFO router.py:222 Router c7200 "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717] has been created
2021-04-29 15:44:50 INFO router.py:1102 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: adapter C7200-IO-FE inserted into slot 0
2021-04-29 15:44:50 INFO router.py:952 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: auto delete disks enabled
2021-04-29 15:44:50 INFO router.py:903 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: disk0 updated from 64MB to 0MB
2021-04-29 15:44:50 INFO router.py:661 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: idle-PC set to 0x606c8480
2021-04-29 15:44:50 INFO router.py:489 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: has a new IOS image set: "/home/saad/GNS3/images/IOS/c7200-is-mz.122-17a.image"
2021-04-29 15:44:50 INFO router.py:1027 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: MAC address updated from ca02.1654.0000 to ca02.7063.0000
2021-04-29 15:44:50 INFO router.py:543 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: NVRAM updated from 128KB to 512KB
2021-04-29 15:44:50 INFO router.py:516 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: RAM updated from 256MB to 512MB
2021-04-29 15:44:50 INFO router.py:1158 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: adapter C7200-IO-FE removed from slot 0
2021-04-29 15:44:50 INFO router.py:1102 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: adapter C7200-IO-2FE inserted into slot 0
2021-04-29 15:44:50 INFO router.py:1102 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: adapter PA-4T+ inserted into slot 1
2021-04-29 15:44:50 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:50 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/dynamips/nodes HTTP/1.1" 201 1365 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:50 INFO web_log.py:206 127.0.0.1 [29/Apr/2021:10:44:50 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:50 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:50 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:50 INFO nio_udp.py:74 NIO UDP udp-9eeb8ba6-d900-4ce7-8501-37626d7c65ab created with lport=10000, rhost=127.0.0.1, rport=10001
2021-04-29 15:44:50 INFO base_node.py:655 Starting new uBridge hypervisor localhost:33279
2021-04-29 15:44:50 INFO hypervisor.py:169 starting ubridge: ['/sbin/ubridge', '-H', 'localhost:33279']
2021-04-29 15:44:50 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/untitled/project-files/dynamips/dedcf55c-74be-4781-9ab0-40961a359022/ubridge.log
2021-04-29 15:44:50 INFO hypervisor.py:179 ubridge started PID=5734
2021-04-29 15:44:50 INFO base_node.py:658 Hypervisor localhost:33279 has successfully started
2021-04-29 15:44:50 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:33279 after 0.1024 seconds
2021-04-29 15:44:50 INFO router.py:1291 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: NIO udp-9eeb8ba6-d900-4ce7-8501-37626d7c65ab bound to port 1/0
2021-04-29 15:44:50 INFO web_log.py:206 127.0.0.1 [29/Apr/2021:10:44:50 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/dynamips/nodes/dedcf55c-74be-4781-9ab0-40961a359022/adapters/1/ports/0/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:50 INFO nio_udp.py:74 NIO UDP udp-59d187eb-84e3-4ed2-bbb7-6783381dd418 created with lport=10001, rhost=127.0.0.1, rport=10000
2021-04-29 15:44:50 INFO base_node.py:655 Starting new uBridge hypervisor localhost:38749
2021-04-29 15:44:50 INFO hypervisor.py:169 starting ubridge: ['/sbin/ubridge', '-H', 'localhost:38749']
2021-04-29 15:44:50 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/untitled/project-files/dynamips/0a8016c9-89ce-48c7-bec1-4b629c469717/ubridge.log
2021-04-29 15:44:50 INFO hypervisor.py:179 ubridge started PID=5745
2021-04-29 15:44:50 INFO base_node.py:658 Hypervisor localhost:38749 has successfully started
2021-04-29 15:44:50 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:38749 after 0.1036 seconds
2021-04-29 15:44:51 INFO router.py:1291 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: NIO udp-59d187eb-84e3-4ed2-bbb7-6783381dd418 bound to port 1/0
2021-04-29 15:44:51 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:50 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/dynamips/nodes/0a8016c9-89ce-48c7-bec1-4b629c469717/adapters/1/ports/0/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:51 INFO web_log.py:206 127.0.0.1 [29/Apr/2021:10:44:51 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:51 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:51 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:51 INFO nio_udp.py:74 NIO UDP udp-2af8b81e-661d-4c64-924c-262f1a2abc13 created with lport=10006, rhost=127.0.0.1, rport=10007
2021-04-29 15:44:51 INFO router.py:1291 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: NIO udp-2af8b81e-661d-4c64-924c-262f1a2abc13 bound to port 0/0
2021-04-29 15:44:51 INFO web_log.py:206 127.0.0.1 [29/Apr/2021:10:44:51 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/dynamips/nodes/dedcf55c-74be-4781-9ab0-40961a359022/adapters/0/ports/0/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:51 INFO docker_vm.py:960 Docker container 'debian-1' [bd98c56c-92f5-4023-9b75-56727eb6ce82]: NIO UDP added to adapter 0
2021-04-29 15:44:51 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:51 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/docker/nodes/bd98c56c-92f5-4023-9b75-56727eb6ce82/adapters/0/ports/0/nio HTTP/1.1" 201 380 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:51 INFO web_log.py:206 127.0.0.1 [29/Apr/2021:10:44:51 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:51 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:51 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:51 INFO nio_udp.py:74 NIO UDP udp-a1864ac8-efb9-43ab-9d62-0660918a0123 created with lport=10010, rhost=127.0.0.1, rport=10011
2021-04-29 15:44:51 INFO router.py:1291 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: NIO udp-a1864ac8-efb9-43ab-9d62-0660918a0123 bound to port 0/0
2021-04-29 15:44:51 INFO web_log.py:206 127.0.0.1 [29/Apr/2021:10:44:51 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/dynamips/nodes/0a8016c9-89ce-48c7-bec1-4b629c469717/adapters/0/ports/0/nio HTTP/1.1" 201 382 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:51 INFO docker_vm.py:960 Docker container 'debian-2' [e113cdc9-d045-410f-9db0-56c48af947a3]: NIO UDP added to adapter 0
2021-04-29 15:44:51 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:51 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/docker/nodes/e113cdc9-d045-410f-9db0-56c48af947a3/adapters/0/ports/0/nio HTTP/1.1" 201 380 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:51 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:49 +0000] "POST /v2/projects/5df9e162-2730-432e-95fa-67089a22eb5a/open HTTP/1.1" 201 742 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:44:51 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:51 +0000] "GET /v2/projects/5df9e162-2730-432e-95fa-67089a22eb5a/nodes HTTP/1.1" 200 13460 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:44:51 INFO project_handler.py:271 New client has connected to the notification stream for project ID '5df9e162-2730-432e-95fa-67089a22eb5a' (WebSocket method)
2021-04-29 15:44:51 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:51 +0000] "GET /v2/projects/5df9e162-2730-432e-95fa-67089a22eb5a/links HTTP/1.1" 200 4117 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:44:51 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:51 +0000] "GET /v2/projects/5df9e162-2730-432e-95fa-67089a22eb5a/drawings HTTP/1.1" 200 205 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:44:55 INFO router.py:110 Creating a new ghost IOS instance
2021-04-29 15:44:55 INFO router.py:489 Router "Ghost" [54f20b0e-5868-410d-b810-795c21281637]: has a new IOS image set: "/home/saad/GNS3/images/IOS/c7200-is-mz.122-17a.image"
2021-04-29 15:44:55 INFO router.py:850 Router "Ghost" [54f20b0e-5868-410d-b810-795c21281637]: ghost status set to 1
2021-04-29 15:44:55 INFO router.py:810 Router "Ghost" [54f20b0e-5868-410d-b810-795c21281637]: ghost file set to "/home/saad/GNS3/projects/untitled/project-files/dynamips/c7200-is-mz.122-17a.image-512.ghost"
2021-04-29 15:44:55 INFO router.py:516 Router "Ghost" [54f20b0e-5868-410d-b810-795c21281637]: RAM updated from 128MB to 512MB
2021-04-29 15:44:56 INFO base_node.py:655 Starting new uBridge hypervisor localhost:45835
2021-04-29 15:44:56 INFO base_node.py:655 Starting new uBridge hypervisor localhost:42253
2021-04-29 15:44:56 INFO hypervisor.py:169 starting ubridge: ['/sbin/ubridge', '-H', 'localhost:45835']
2021-04-29 15:44:56 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/untitled/project-files/docker/e113cdc9-d045-410f-9db0-56c48af947a3/ubridge.log
2021-04-29 15:44:56 INFO hypervisor.py:179 ubridge started PID=5940
2021-04-29 15:44:56 INFO base_node.py:658 Hypervisor localhost:45835 has successfully started
2021-04-29 15:44:56 INFO hypervisor.py:169 starting ubridge: ['/sbin/ubridge', '-H', 'localhost:42253']
2021-04-29 15:44:56 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/untitled/project-files/docker/bd98c56c-92f5-4023-9b75-56727eb6ce82/ubridge.log
2021-04-29 15:44:56 INFO hypervisor.py:179 ubridge started PID=5944
2021-04-29 15:44:56 INFO base_node.py:658 Hypervisor localhost:42253 has successfully started
2021-04-29 15:44:56 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:45835 after 0.1027 seconds
2021-04-29 15:44:56 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:42253 after 0.1018 seconds
2021-04-29 15:44:56 INFO router.py:298 router "Ghost" [54f20b0e-5868-410d-b810-795c21281637] has been started
2021-04-29 15:44:56 INFO docker_vm.py:499 Docker container 'debian-2' [debian:latest] started listen for telnet on 5004
2021-04-29 15:44:56 INFO web_log.py:206 127.0.0.1 [29/Apr/2021:10:44:55 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/docker/nodes/e113cdc9-d045-410f-9db0-56c48af947a3/start HTTP/1.1" 204 228 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:56 INFO docker_vm.py:499 Docker container 'debian-1' [debian:latest] started listen for telnet on 5002
2021-04-29 15:44:56 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:55 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/docker/nodes/bd98c56c-92f5-4023-9b75-56727eb6ce82/start HTTP/1.1" 204 228 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:56 INFO router.py:328 Router "Ghost" [54f20b0e-5868-410d-b810-795c21281637] has been stopped
2021-04-29 15:44:56 INFO router.py:1638 Router "Ghost" [54f20b0e-5868-410d-b810-795c21281637] has been deleted (including associated files)
2021-04-29 15:44:56 INFO router.py:850 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: ghost status set to 2
2021-04-29 15:44:56 INFO router.py:810 Router "R1" [dedcf55c-74be-4781-9ab0-40961a359022]: ghost file set to "/home/saad/GNS3/projects/untitled/project-files/dynamips/c7200-is-mz.122-17a.image-512.ghost"
2021-04-29 15:44:56 INFO router.py:850 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: ghost status set to 2
2021-04-29 15:44:56 INFO router.py:810 Router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717]: ghost file set to "/home/saad/GNS3/projects/untitled/project-files/dynamips/c7200-is-mz.122-17a.image-512.ghost"
2021-04-29 15:44:56 INFO router.py:298 router "R2" [0a8016c9-89ce-48c7-bec1-4b629c469717] has been started
2021-04-29 15:44:56 INFO web_log.py:206 127.0.0.1 [29/Apr/2021:10:44:56 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/dynamips/nodes/0a8016c9-89ce-48c7-bec1-4b629c469717/start HTTP/1.1" 204 230 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:56 INFO router.py:298 router "R1" [dedcf55c-74be-4781-9ab0-40961a359022] has been started
2021-04-29 15:44:56 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:55 +0000] "POST /v2/compute/projects/5df9e162-2730-432e-95fa-67089a22eb5a/dynamips/nodes/dedcf55c-74be-4781-9ab0-40961a359022/start HTTP/1.1" 204 230 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-04-29 15:44:56 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:55 +0000] "POST /v2/projects/5df9e162-2730-432e-95fa-67089a22eb5a/nodes/start HTTP/1.1" 204 203 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:44:57 INFO web_log.py:206 ::1 [29/Apr/2021:10:44:57 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:45:26 INFO router.py:1599 saving startup-config to /home/saad/GNS3/projects/untitled/project-files/dynamips/0a8016c9-89ce-48c7-bec1-4b629c469717/configs/i2_startup-config.cfg
2021-04-29 15:45:26 INFO router.py:1599 saving startup-config to /home/saad/GNS3/projects/untitled/project-files/dynamips/dedcf55c-74be-4781-9ab0-40961a359022/configs/i1_startup-config.cfg
2021-04-29 15:46:23 INFO web_log.py:206 ::1 [29/Apr/2021:10:46:23 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:50:48 INFO web_log.py:206 ::1 [29/Apr/2021:10:50:48 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:27 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:27 +0000] "PUT /v2/projects/5df9e162-2730-432e-95fa-67089a22eb5a/links/c60d4087-9145-4895-addf-d14a4559217a HTTP/1.1" 201 1370 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:34 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:34 +0000] "GET /v2/symbols HTTP/1.1" 200 66410 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:34 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:34 +0000] "GET /v2/symbols/%3A/symbols/affinity/circle/red/client.svg/raw HTTP/1.1" 200 3376 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:34 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:34 +0000] "GET /v2/symbols/%3A/symbols/classic/access_point.svg/raw HTTP/1.1" 200 260613 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:34 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:34 +0000] "GET /v2/symbols/%3A/symbols/affinity/circle/gray/communications.svg/raw HTTP/1.1" 200 3371 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:34 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:34 +0000] "GET /v2/symbols/multilayer_switch4.svg/raw HTTP/1.1" 200 8445 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:34 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:34 +0000] "GET /v2/symbols/%3A/symbols/affinity/circle/red/pinpoint.svg/raw HTTP/1.1" 200 2839 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:34 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:34 +0000] "GET /v2/symbols/%3A/symbols/classic/route_switch_processor.svg/raw HTTP/1.1" 200 25208 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:35 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:35 +0000] "GET /v2/symbols/%3A/symbols/affinity/square/blue/square.svg/raw HTTP/1.1" 200 2348 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:35 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:35 +0000] "GET /v2/symbols/%3A/symbols/affinity/square/gray/square.svg/raw HTTP/1.1" 200 2348 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:35 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:35 +0000] "GET /v2/symbols/%3A/symbols/affinity/square/blue/wifi.svg/raw HTTP/1.1" 200 4802 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:35 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:35 +0000] "GET /v2/symbols/%3A/symbols/classic/vpcs_guest.svg/raw HTTP/1.1" 200 19495 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:35 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:35 +0000] "GET /v2/symbols/workgroundswitch3.svg/raw HTTP/1.1" 200 4835 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:35 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:35 +0000] "GET /v2/symbols/workgroundswitch.svg/raw HTTP/1.1" 200 5101 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:35 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:35 +0000] "GET /v2/symbols/%3A/symbols/affinity/square/blue/xml.svg/raw HTTP/1.1" 200 4029 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:54:49 INFO web_log.py:206 ::1 [29/Apr/2021:10:54:49 +0000] "PUT /v2/templates/a73aa422-cc62-44cc-80c0-db7509da35c1 HTTP/1.1" 200 1167 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:55:24 INFO web_log.py:206 ::1 [29/Apr/2021:10:55:24 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.20"
2021-04-29 15:59:55 INFO web_log.py:206 ::1 [29/Apr/2021:10:59:55 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-29 16:04:37 INFO web_log.py:206 ::1 [29/Apr/2021:11:04:37 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-29 16:04:39 INFO web_log.py:206 ::1 [29/Apr/2021:11:04:39 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
