2021-04-10 11:03:37 INFO run.py:219 GNS3 server version 2.2.20
2021-04-10 11:03:37 INFO run.py:221 Copyright (c) 2007-2021 GNS3 Technologies Inc.
2021-04-10 11:03:37 INFO run.py:224 Config file /home/saad/.config/GNS3/2.2/gns3_server.conf loaded
2021-04-10 11:03:37 WARNING run.py:230 Local mode is enabled. Beware, clients will have full control on your filesystem
2021-04-10 11:03:37 INFO run.py:243 Running with Python 3.9.2 and has PID 11278
2021-04-10 11:03:37 WARNING run.py:66 Could not find a default locale, switching to C.UTF-8...
2021-04-10 11:03:37 WARNING port_manager.py:92 Remote console connections are allowed
2021-04-10 11:03:37 INFO web_server.py:318 Starting server on localhost:3080
2021-04-10 11:03:37 INFO __init__.py:63 Load controller configuration file /home/saad/.config/GNS3/2.2/gns3_controller.conf
2021-04-10 11:03:37 INFO __init__.py:67 Controller is starting
2021-04-10 11:03:37 INFO compute.py:64 Create compute local
2021-04-10 11:03:37 INFO compute.py:364 Connecting to compute 'local'
2021-04-10 11:03:37 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:03:37 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 552 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:03:38 INFO web_log.py:206 ::1 [10/Apr/2021:11:03:38 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:03:38 INFO notification_handler.py:50 New client has connected to compute WebSocket
2021-04-10 11:03:38 INFO compute.py:434 Connected to compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws'
2021-04-10 11:03:38 INFO web_log.py:206 ::1 [10/Apr/2021:11:03:38 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:03:38 INFO notification_handler.py:73 New client has connected to controller WebSocket
2021-04-10 11:03:38 INFO web_log.py:206 ::1 [10/Apr/2021:11:03:38 +0000] "GET /v2/templates HTTP/1.1" 200 17101 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:03:38 INFO web_log.py:206 ::1 [10/Apr/2021:11:03:38 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:03:38 INFO web_log.py:206 ::1 [10/Apr/2021:11:03:38 +0000] "GET /v2/appliances?symbol_theme=Affinity-circle-gray HTTP/1.1" 200 790748 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:03:38 INFO web_log.py:206 ::1 [10/Apr/2021:11:03:38 +0000] "GET /v2/projects HTTP/1.1" 200 25583 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:03:38 INFO web_log.py:206 ::1 [10/Apr/2021:11:03:38 +0000] "GET /v2/projects HTTP/1.1" 200 25583 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:03:43 INFO project.py:78 Project 2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 with path '/home/saad/GNS3/projects/lab_for_programming' created
2021-04-10 11:03:43 INFO web_log.py:206 ::1 [10/Apr/2021:11:03:43 +0000] "POST /v2/compute/projects HTTP/1.1" 201 314 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:03:43 INFO iou_vm.py:73 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: assigned with application ID 1
2021-04-10 11:03:43 INFO iou_vm.py:848 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: number of Ethernet adapters changed to 2
2021-04-10 11:03:43 INFO iou_vm.py:876 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: number of Serial adapters changed to 2
2021-04-10 11:03:43 INFO iou_vm.py:316 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: NVRAM updated from 128KB to 64KB
2021-04-10 11:03:43 INFO iou_vm.py:848 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: number of Ethernet adapters changed to 3
2021-04-10 11:03:43 INFO iou_vm.py:145 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin"
2021-04-10 11:03:43 INFO iou_vm.py:876 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: number of Serial adapters changed to 1
2021-04-10 11:03:43 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:03:43 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes HTTP/1.1" 201 881 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:03:43 INFO iou_vm.py:73 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: assigned with application ID 2
2021-04-10 11:03:43 INFO iou_vm.py:848 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: number of Ethernet adapters changed to 2
2021-04-10 11:03:43 INFO iou_vm.py:876 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: number of Serial adapters changed to 2
2021-04-10 11:03:43 INFO iou_vm.py:316 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: NVRAM updated from 128KB to 16KB
2021-04-10 11:03:43 INFO iou_vm.py:848 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: number of Ethernet adapters changed to 4
2021-04-10 11:03:43 INFO iou_vm.py:145 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.1a.bin"
2021-04-10 11:03:43 INFO iou_vm.py:876 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: number of Serial adapters changed to 0
2021-04-10 11:03:43 INFO web_log.py:206 ::1 [10/Apr/2021:11:03:43 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes HTTP/1.1" 201 876 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:03:43 INFO docker_vm.py:1058 Docker container "debian-1" [12019ce8-f8ff-4a54-b226-3fc9f4b4b4c2]: number of Ethernet adapters changed to 1
2021-04-10 11:03:43 INFO docker_vm.py:406 Docker container 'debian-1' [12019ce8-f8ff-4a54-b226-3fc9f4b4b4c2] created
2021-04-10 11:03:43 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:03:43 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/docker/nodes HTTP/1.1" 201 935 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:03:43 ERROR route.py:217 Node error detected: NodeError
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.9/site-packages/gns3server/handlers/api/compute/nat_handler.py", line 55, in create
    node = await builtin_manager.create_node(request.json.pop("name"),
  File "/usr/lib/python3.9/site-packages/gns3server/compute/base_manager.py", line 257, in create_node
    node = self._NODE_CLASS(name, node_id, project, self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/gns3server/compute/builtin/builtin_node_factory.py", line 45, in __new__
    return BUILTIN_NODES[node_type](name, node_id, project, manager, **kwargs)
  File "/usr/lib/python3.9/site-packages/gns3server/compute/builtin/nodes/nat.py", line 41, in __init__
    raise NodeError("NAT interface {} is missing, please install libvirt".format(nat_interface))
gns3server.compute.error.NodeError: NAT interface virbr0 is missing, please install libvirt
2021-04-10 11:03:43 INFO web_log.py:206 ::1 [10/Apr/2021:11:03:43 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/nat/nodes HTTP/1.1" 409 345 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:03:43 INFO base_node.py:331 IOU: 'S1' [c627637e-2cf0-4ca2-828d-53d39361b357]: is closing
2021-04-10 11:03:43 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/c627637e-2cf0-4ca2-828d-53d39361b357/startup-config.cfg
2021-04-10 11:03:43 INFO iou_vm.py:1278 saving private-config to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/c627637e-2cf0-4ca2-828d-53d39361b357/private-config.cfg
2021-04-10 11:03:43 INFO base_node.py:331 IOU: 'R1' [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: is closing
2021-04-10 11:03:43 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/526b3262-a87e-4f9b-ad6e-30c40ecdf14c/startup-config.cfg
2021-04-10 11:03:43 INFO iou_vm.py:1278 saving private-config to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/526b3262-a87e-4f9b-ad6e-30c40ecdf14c/private-config.cfg
2021-04-10 11:03:43 INFO base_node.py:331 Docker: 'debian-1' [12019ce8-f8ff-4a54-b226-3fc9f4b4b4c2]: is closing
2021-04-10 11:03:44 INFO docker_vm.py:872 Docker container 'debian-1' [debian:latest] removed
2021-04-10 11:03:44 INFO project.py:361 Project 2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 with path '/home/saad/GNS3/projects/lab_for_programming' closed
2021-04-10 11:03:44 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:03:43 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/close HTTP/1.1" 204 205 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:03:44 INFO web_log.py:206 ::1 [10/Apr/2021:11:03:43 +0000] "POST /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/open HTTP/1.1" 409 301 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:06:33 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:33 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:06:33 INFO project.py:78 Project 2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 with path '/home/saad/GNS3/projects/lab_for_programming' created
2021-04-10 11:06:33 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects HTTP/1.1" 201 314 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO iou_vm.py:73 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: assigned with application ID 1
2021-04-10 11:06:33 INFO iou_vm.py:848 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: number of Ethernet adapters changed to 2
2021-04-10 11:06:33 INFO iou_vm.py:876 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: number of Serial adapters changed to 2
2021-04-10 11:06:33 INFO iou_vm.py:316 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: NVRAM updated from 128KB to 64KB
2021-04-10 11:06:33 INFO iou_vm.py:848 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: number of Ethernet adapters changed to 3
2021-04-10 11:06:33 INFO iou_vm.py:145 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin"
2021-04-10 11:06:33 INFO iou_vm.py:876 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: number of Serial adapters changed to 1
2021-04-10 11:06:33 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes HTTP/1.1" 201 881 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO iou_vm.py:73 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: assigned with application ID 2
2021-04-10 11:06:33 INFO iou_vm.py:848 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: number of Ethernet adapters changed to 2
2021-04-10 11:06:33 INFO iou_vm.py:876 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: number of Serial adapters changed to 2
2021-04-10 11:06:33 INFO iou_vm.py:316 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: NVRAM updated from 128KB to 16KB
2021-04-10 11:06:33 INFO iou_vm.py:848 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: number of Ethernet adapters changed to 4
2021-04-10 11:06:33 INFO iou_vm.py:145 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.1a.bin"
2021-04-10 11:06:33 INFO iou_vm.py:876 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: number of Serial adapters changed to 0
2021-04-10 11:06:33 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes HTTP/1.1" 201 876 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO docker_vm.py:1058 Docker container "debian-1" [12019ce8-f8ff-4a54-b226-3fc9f4b4b4c2]: number of Ethernet adapters changed to 1
2021-04-10 11:06:33 INFO docker_vm.py:406 Docker container 'debian-1' [12019ce8-f8ff-4a54-b226-3fc9f4b4b4c2] created
2021-04-10 11:06:33 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/docker/nodes HTTP/1.1" 201 935 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO nat.py:51 NAT node 'NAT1' configured to use NAT interface 'virbr0'
2021-04-10 11:06:33 INFO base_node.py:655 Starting new uBridge hypervisor localhost:40083
2021-04-10 11:06:33 INFO hypervisor.py:169 starting ubridge: ['/sbin/ubridge', '-H', 'localhost:40083']
2021-04-10 11:06:33 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/lab_for_programming/project-files/builtin/ca859fb8-59bf-4a2a-abd1-6b3d3157defb/ubridge.log
2021-04-10 11:06:33 INFO hypervisor.py:179 ubridge started PID=12487
2021-04-10 11:06:33 INFO base_node.py:658 Hypervisor localhost:40083 has successfully started
2021-04-10 11:06:33 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:40083 after 0.1036 seconds
2021-04-10 11:06:33 INFO cloud.py:215 Cloud "NAT1" [ca859fb8-59bf-4a2a-abd1-6b3d3157defb] has been created
2021-04-10 11:06:33 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/nat/nodes HTTP/1.1" 201 553 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO docker_vm.py:960 Docker container 'debian-1' [12019ce8-f8ff-4a54-b226-3fc9f4b4b4c2]: NIO UDP added to adapter 0
2021-04-10 11:06:33 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/docker/nodes/12019ce8-f8ff-4a54-b226-3fc9f4b4b4c2/adapters/0/ports/0/nio HTTP/1.1" 201 380 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO iou_vm.py:902 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: NIO UDP added to 0/0
2021-04-10 11:06:33 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/c627637e-2cf0-4ca2-828d-53d39361b357/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO iou_vm.py:902 IOU "S1" [c627637e-2cf0-4ca2-828d-53d39361b357]: NIO UDP added to 0/1
2021-04-10 11:06:33 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/c627637e-2cf0-4ca2-828d-53d39361b357/adapters/0/ports/1/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO iou_vm.py:902 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: NIO UDP added to 0/0
2021-04-10 11:06:33 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/526b3262-a87e-4f9b-ad6e-30c40ecdf14c/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO iou_vm.py:902 IOU "R1" [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: NIO UDP added to 0/1
2021-04-10 11:06:33 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/526b3262-a87e-4f9b-ad6e-30c40ecdf14c/adapters/0/ports/1/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO cloud.py:396 Cloud "NAT1" [ca859fb8-59bf-4a2a-abd1-6b3d3157defb]: NIO NIO UDP bound to port 0
2021-04-10 11:06:33 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:33 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/nat/nodes/ca859fb8-59bf-4a2a-abd1-6b3d3157defb/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:33 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:33 +0000] "POST /v2/projects/load HTTP/1.1" 201 761 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:06:33 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:33 +0000] "GET /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/nodes HTTP/1.1" 200 17680 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:06:33 INFO project_handler.py:271 New client has connected to the notification stream for project ID '2a56fee1-bb43-4cda-a5f5-1ab3c90677e4' (WebSocket method)
2021-04-10 11:06:33 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:33 +0000] "GET /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/links HTTP/1.1" 200 4120 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:06:33 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:33 +0000] "GET /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/drawings HTTP/1.1" 200 2717 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:06:36 INFO iou_vm.py:414 Checking IOU license in '/tmp/tmpkkx3d3s2/iourc'
2021-04-10 11:06:36 INFO iou_vm.py:414 Checking IOU license in '/tmp/tmpjbfwnps2/iourc'
2021-04-10 11:06:36 INFO base_node.py:655 Starting new uBridge hypervisor localhost:42249
2021-04-10 11:06:36 INFO base_node.py:655 Starting new uBridge hypervisor localhost:44289
2021-04-10 11:06:36 INFO hypervisor.py:169 starting ubridge: ['/sbin/ubridge', '-H', 'localhost:42249']
2021-04-10 11:06:36 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/c627637e-2cf0-4ca2-828d-53d39361b357/ubridge.log
2021-04-10 11:06:36 INFO hypervisor.py:179 ubridge started PID=12540
2021-04-10 11:06:36 INFO base_node.py:658 Hypervisor localhost:42249 has successfully started
2021-04-10 11:06:36 INFO hypervisor.py:169 starting ubridge: ['/sbin/ubridge', '-H', 'localhost:44289']
2021-04-10 11:06:36 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/526b3262-a87e-4f9b-ad6e-30c40ecdf14c/ubridge.log
2021-04-10 11:06:36 INFO hypervisor.py:179 ubridge started PID=12554
2021-04-10 11:06:36 INFO base_node.py:658 Hypervisor localhost:44289 has successfully started
2021-04-10 11:06:36 INFO base_node.py:655 Starting new uBridge hypervisor localhost:45047
2021-04-10 11:06:36 INFO hypervisor.py:169 starting ubridge: ['/sbin/ubridge', '-H', 'localhost:45047']
2021-04-10 11:06:36 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/lab_for_programming/project-files/docker/12019ce8-f8ff-4a54-b226-3fc9f4b4b4c2/ubridge.log
2021-04-10 11:06:36 INFO hypervisor.py:179 ubridge started PID=12608
2021-04-10 11:06:36 INFO base_node.py:658 Hypervisor localhost:45047 has successfully started
2021-04-10 11:06:36 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:42249 after 0.1056 seconds
2021-04-10 11:06:36 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:44289 after 0.1017 seconds
2021-04-10 11:06:37 INFO iou_vm.py:753 IOU S1 [id=c627637e-2cf0-4ca2-828d-53d39361b357]: NETMAP file created
2021-04-10 11:06:37 INFO iou_vm.py:753 IOU R1 [id=526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: NETMAP file created
2021-04-10 11:06:37 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:45047 after 0.1152 seconds
2021-04-10 11:06:37 INFO iou_vm.py:551 Starting IOU: ['/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin', '-e', '3', '-s', '1', '1']
2021-04-10 11:06:37 INFO iou_vm.py:551 Starting IOU: ['/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.1a.bin', '-e', '4', '-s', '0', '2']
2021-04-10 11:06:37 INFO iou_vm.py:560 IOU instance 526b3262-a87e-4f9b-ad6e-30c40ecdf14c started PID=12621
2021-04-10 11:06:37 INFO iou_vm.py:560 IOU instance c627637e-2cf0-4ca2-828d-53d39361b357 started PID=12623
2021-04-10 11:06:37 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:36 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/526b3262-a87e-4f9b-ad6e-30c40ecdf14c/start HTTP/1.1" 200 976 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:37 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:06:36 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/c627637e-2cf0-4ca2-828d-53d39361b357/start HTTP/1.1" 200 966 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:37 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:37 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/nat/nodes/ca859fb8-59bf-4a2a-abd1-6b3d3157defb/start HTTP/1.1" 204 225 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:37 INFO docker_vm.py:499 Docker container 'debian-1' [debian:latest] started listen for telnet on 5005
2021-04-10 11:06:37 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:06:36 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/docker/nodes/12019ce8-f8ff-4a54-b226-3fc9f4b4b4c2/start HTTP/1.1" 204 228 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 11:06:37 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:36 +0000] "POST /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/nodes/start HTTP/1.1" 204 203 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:06:38 INFO web_log.py:206 ::1 [10/Apr/2021:11:06:38 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:11:42 INFO web_log.py:206 ::1 [10/Apr/2021:11:11:42 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:17:31 INFO web_log.py:206 ::1 [10/Apr/2021:11:17:31 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:23:29 INFO web_log.py:206 ::1 [10/Apr/2021:11:23:29 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:28:17 INFO web_log.py:206 ::1 [10/Apr/2021:11:28:17 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:32:43 INFO web_log.py:206 ::1 [10/Apr/2021:11:32:43 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:39:07 INFO web_log.py:206 ::1 [10/Apr/2021:11:39:07 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:44:11 INFO web_log.py:206 ::1 [10/Apr/2021:11:44:11 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:50:01 INFO web_log.py:206 ::1 [10/Apr/2021:11:50:01 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.20"
2021-04-10 11:55:48 INFO web_log.py:206 ::1 [10/Apr/2021:11:55:48 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-10 12:00:44 INFO web_log.py:206 ::1 [10/Apr/2021:12:00:44 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-10 12:00:46 INFO web_log.py:206 ::1 [10/Apr/2021:12:00:46 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-10 12:06:32 INFO web_log.py:206 ::1 [10/Apr/2021:12:06:32 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.20"
2021-04-10 12:11:18 INFO web_log.py:206 ::1 [10/Apr/2021:12:11:18 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-10 12:17:07 INFO web_log.py:206 ::1 [10/Apr/2021:12:17:07 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-10 12:21:49 INFO web_log.py:206 ::1 [10/Apr/2021:12:21:49 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.20"
2021-04-10 12:25:49 INFO web_log.py:206 ::1 [10/Apr/2021:12:25:49 +0000] "PUT /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 HTTP/1.1" 200 322 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 12:25:49 INFO web_log.py:206 ::1 [10/Apr/2021:12:25:49 +0000] "PUT /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 HTTP/1.1" 200 765 "-" "GNS3 QT Client v2.2.20"
2021-04-10 12:25:49 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:12:25:49 +0000] "PUT /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 HTTP/1.1" 200 322 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 12:25:49 INFO web_log.py:206 ::1 [10/Apr/2021:12:25:49 +0000] "PUT /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 HTTP/1.1" 200 765 "-" "GNS3 QT Client v2.2.20"
2021-04-10 12:25:49 INFO web_log.py:206 ::1 [10/Apr/2021:12:25:49 +0000] "PUT /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 HTTP/1.1" 200 322 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 12:25:49 INFO web_log.py:206 ::1 [10/Apr/2021:12:25:49 +0000] "PUT /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 HTTP/1.1" 200 765 "-" "GNS3 QT Client v2.2.20"
2021-04-10 12:25:51 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:12:25:51 +0000] "PUT /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 HTTP/1.1" 200 322 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 12:25:51 INFO web_log.py:206 ::1 [10/Apr/2021:12:25:51 +0000] "PUT /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 HTTP/1.1" 200 764 "-" "GNS3 QT Client v2.2.20"
2021-04-10 12:25:51 INFO web_log.py:206 ::1 [10/Apr/2021:12:25:51 +0000] "PUT /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 HTTP/1.1" 200 322 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 12:25:51 INFO web_log.py:206 ::1 [10/Apr/2021:12:25:51 +0000] "PUT /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 HTTP/1.1" 200 764 "-" "GNS3 QT Client v2.2.20"
2021-04-10 12:25:52 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:12:25:52 +0000] "PUT /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 HTTP/1.1" 200 322 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 12:25:52 INFO web_log.py:206 ::1 [10/Apr/2021:12:25:52 +0000] "PUT /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 HTTP/1.1" 200 764 "-" "GNS3 QT Client v2.2.20"
2021-04-10 12:25:54 INFO web_log.py:206 ::1 [10/Apr/2021:12:25:54 +0000] "PUT /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 HTTP/1.1" 200 322 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 12:25:54 INFO web_log.py:206 ::1 [10/Apr/2021:12:25:54 +0000] "PUT /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 HTTP/1.1" 200 765 "-" "GNS3 QT Client v2.2.20"
2021-04-10 12:28:03 WARNING web_server.py:170 Server has got signal SIGTERM, exiting...
2021-04-10 12:28:03 INFO web_server.py:167 Server has got signal SIGHUP, reloading...
2021-04-10 12:28:03 INFO web_server.py:113 Closing 3 websocket connections...
2021-04-10 12:28:03 INFO __init__.py:154 Controller is reloading
2021-04-10 12:28:03 INFO iou_vm.py:698 Stopping IOU process for IOU VM "S1" PID=12623
2021-04-10 12:28:03 INFO iou_vm.py:698 Stopping IOU process for IOU VM "R1" PID=12621
2021-04-10 12:28:03 INFO compute.py:460 Connection closed to compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws'
2021-04-10 12:28:03 INFO notification_handler.py:59 Client has disconnected from compute WebSocket
2021-04-10 12:28:03 INFO web_log.py:206 127.0.0.1 [10/Apr/2021:11:03:38 +0000] "GET /v2/compute/notifications/ws HTTP/1.1" 200 445 "-" "Python/3.9 aiohttp/3.7.4"
2021-04-10 12:28:03 INFO notification_handler.py:82 Client has disconnected from controller WebSocket
2021-04-10 12:28:03 INFO project_handler.py:280 Client has disconnected from notification stream for project ID '2a56fee1-bb43-4cda-a5f5-1ab3c90677e4' (WebSocket method)
2021-04-10 12:28:03 INFO __init__.py:138 Controller is stopping
2021-04-10 12:28:03 INFO base_node.py:331 Builtin: 'NAT1' [ca859fb8-59bf-4a2a-abd1-6b3d3157defb]: is closing
2021-04-10 12:28:03 INFO cloud.py:248 Cloud "NAT1" [ca859fb8-59bf-4a2a-abd1-6b3d3157defb] has been closed
2021-04-10 12:28:03 INFO base_node.py:331 Docker: 'debian-1' [12019ce8-f8ff-4a54-b226-3fc9f4b4b4c2]: is closing
2021-04-10 12:28:04 INFO docker_vm.py:533 Docker container 'debian-1' fix ownership, state = exited
2021-04-10 12:28:04 INFO docker_vm.py:872 Docker container 'debian-1' [debian:latest] removed
2021-04-10 12:28:04 ERROR base_events.py:1738 Task exception was never retrieved
future: <Task finished name='Task-651' coro=<DockerVM._read_console_output() done, defined at /usr/lib/python3.9/site-packages/gns3server/compute/docker/docker_vm.py:710> exception=Docker has returned an error: [Errno 32] Broken pipe>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gns3server/compute/docker/__init__.py", line 147, in http_query
    response = await self._session.request(method,
  File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/lib/python3.9/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gns3server/compute/docker/docker_vm.py", line 730, in _read_console_output
    await self.stop()
  File "/usr/lib/python3.9/site-packages/gns3server/compute/docker/docker_vm.py", line 786, in stop
    await self._fix_permissions()
  File "/usr/lib/python3.9/site-packages/gns3server/compute/docker/docker_vm.py", line 536, in _fix_permissions
    await self.manager.query("POST", "containers/{}/start".format(self._cid))
  File "/usr/lib/python3.9/site-packages/gns3server/compute/docker/__init__.py", line 110, in query
    response = await self.http_query(method, path, data=data, params=params)
  File "/usr/lib/python3.9/site-packages/gns3server/compute/docker/__init__.py", line 154, in http_query
    raise DockerError("Docker has returned an error: {}".format(str(e)))
gns3server.compute.docker.docker_error.DockerError: Docker has returned an error: [Errno 32] Broken pipe
2021-04-10 12:28:04 INFO base_node.py:331 IOU: 'R1' [526b3262-a87e-4f9b-ad6e-30c40ecdf14c]: is closing
2021-04-10 12:28:04 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/526b3262-a87e-4f9b-ad6e-30c40ecdf14c/startup-config.cfg
2021-04-10 12:28:04 INFO iou_vm.py:1278 saving private-config to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/526b3262-a87e-4f9b-ad6e-30c40ecdf14c/private-config.cfg
2021-04-10 12:28:04 INFO base_node.py:331 IOU: 'S1' [c627637e-2cf0-4ca2-828d-53d39361b357]: is closing
2021-04-10 12:28:04 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/c627637e-2cf0-4ca2-828d-53d39361b357/startup-config.cfg
2021-04-10 12:28:04 INFO iou_vm.py:1278 saving private-config to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/c627637e-2cf0-4ca2-828d-53d39361b357/private-config.cfg
2021-04-10 12:28:04 INFO run.py:272 Remove PID file /home/saad/.config/GNS3/2.2/gns3_server.pid
